# theme: hacker
title: Boats' crappy blog
author: Federico Voges
description: probably another blog with no posts
timezone: Europe/London
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
